---
  - name: Check OS support
    debug: msg="The following OS family {{ ansible_os_family }} {{ ansible_architecture }} is not supported" fail=yes
    when: not ansible_os_family == "RedHat" or not ansible_architecture == "x86_64"

  - name: Check packet manager support
    debug: msg="The following packet manager {{ ansible_pkg_mgr }} is not supported" fail=yes
    when: not ansible_pkg_mgr == "yum"

  - name: Upgrade all packages used on the hosts
    yum: name=* state=latest
