---
- name: ensure packages are installed
  apt: name={{item}}
  with_items:
    - postgresql-server
    - postgresql-contrib

- name: ensure database is created
  sudo: yes
  sudo_user: postgres
  postgresql_db:
    name: "{{ db_name }}"

- name: ensure user has access to database
  sudo: yes
  sudo_user: postgres
  postgresql_user:
    db: "{{ db_name }}"
    name: "{{ db_user }}"
    password: "{{ db_password }}"
    priv: ALL

- name: ensure user does not have unnecessary privilege
  sudo: yes
  sudo_user: postgres
  postgresql_user:
    name: "{{ db_user }}"
    role_attr_flags: NOSUPERUSER,NOCREATEDB
