---
- name: Ensure packages are installed
  yum: name={{item}}
  with_items:
    - postgresql-server
    - postgresql-contrib
    - python-psycopg2

- name: Ensure initdb is run
  command: "postgresql-setup initdb"

- name: Restart postgresql service
  service: name="postgresql" state=started enabled=yes

- name: Ensure database is created
  sudo: yes
  sudo_user: postgres
  postgresql_db:
    name: "{{ db_name }}"

- name: Ensure user has access to database
  sudo: yes
  sudo_user: postgres
  postgresql_user:
    db: "{{ db_name }}"
    name: "{{ db_user }}"
    password: "{{ db_password }}"
    priv: ALL

- name: Ensure user does not have unnecessary privilege
  sudo: yes
  sudo_user: postgres
  postgresql_user:
    name: "{{ db_user }}"
    role_attr_flags: NOSUPERUSER,NOCREATEDB

- name: "Configure postgresql.conf"
  lineinfile:
    dest: "/var/lib/pgsql/data/postgresql.conf"
    state: present
    regexp: "{{ item.regexp }}"
    line: "{{ item.guc }}"
  with_items: postgresql_conf_default_guc

- name: "Configure pg_hba.conf"
  template:
    src: pg_hba.conf.j2
    dest: "/var/lib/pgsql/data/pg_hba.conf"
    owner: "{{ postgresql_admin_user }}"
    group: "{{ postgresql_admin_user }}"
    mode: 0640

- name: "Create postgresql log directory"
  file:
    path: "{{ postgresql_log_directory }}"
    state: directory
    owner: "{{ postgresql_admin_user }}"
    group: "{{ postgresql_admin_user }}"
    mode: 0755
  when: postgresql_log_directory is defined

- name: Reload postgresql service
  service: name="postgresql" state=reloaded
